version: 2
jobs:
  test-3.7:
    docker:
      - image: circleci/python:3.7
    working_directory: ~/repo
    steps:
      - checkout
      # Download and cache dependencies

      - run:
          name: Install Dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -e .[test]

      - run: 
          name: Run Tests
          command: |
            . venv/bin/activate
            python3 -m pytest

  test-3.6:
    docker:
      - image: circleci/python:3.6
    working_directory: ~/repo
    steps:
      - checkout

      - run:
          name: Install Dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -e .[test]

      - run: 
          name: Run Tests
          command: |
            . venv/bin/activate
            python3 -m pytest

  test-3.5:
    docker:
      - image: circleci/python:3.5
    working_directory: ~/repo
    steps:
      - checkout

      - run:
          name: Install Dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -e .[test]

      - run: 
          name: Run Tests
          command: |
            . venv/bin/activate
            python3 -m pytest

  test-3.4:
    docker:
      - image: circleci/python:3.4
    working_directory: ~/repo
    steps:
      - checkout

      - run:
          name: Install Dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -e .[test]

      - run: 
          name: Run Tests
          command: |
            . venv/bin/activate
            python3 -m pytest



  release:
    docker:
      - image: circleci/python:3.7
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "setup.py" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      
      - run:
          name: Activate Virtual Environment
          command: |
            python3 -m venv venv
            . venv/bin/activate
      
      - run: 
          name: Package Library
          command: python3 setup.py sdist bdist_wheel

      - run: 
          name: Install JFrog CLI
          command: bash -c 'curl -fL https://getcli.jfrog.io | sh'

      - run: 
          name: Configure JFrog CLI
          command: ./jfrog rt config --url $ARTIFACTORY_URL --user $ARTIFACTORY_USER --apikey $ARTIFACTORY_API_KEY --interactive=false
      
      - run: 
          name: Release Build to Artifactory
          command: ./jfrog rt u "dist/(CodaClient*)" /pypi-local/codaclient/{1} --recursive=false 

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - test-3.7
      - test-3.6
      - test-3.5
      - release:
          requires:
            - test-3.7
            - test-3.6
            - test-3.5
          filters:
            branches:
              only: master